#!/bin/bash

# Start geth (add the --fast parameter if this is the initial download)
echo "Starting geth in Screen. Output to .ethereum/testnet/geth.log"
screen -dmS geth_daemon bash -c '/usr/bin/geth --testnet --fast --cache=2048 2> /home/pilot114/.ethereum/testnet/geth.log'

# Tail the log file
gnome-terminal -e "bash -c \"tail -f /home/pilot114/.ethereum/testnet/geth.log\""

sleep 10

# Attach to the console
geth --preload "/home/pilot114/projects/voting/ethereumDB/scripts/gethload.js" attach ipc:/home/mattie432/.ethereum/testnet/geth.ipc
